Docs
ITMO-NSS-team/torch_DE_solver pull request #22
Opened 2023-02-22 13:17 UTC by nikiniki1

2023-03-08 18:03 UTC, SuperSashka commented on tedeous/metrics.py
> +            smth
Надо сюда написать что метод returns

2023-03-11 14:08 UTC, SuperSashka requested changes
Дамир проверил все примеры, ничего не ломается, вроде. Исправь мои два коммента, сделай ребейз, разреши конфликты, да и можно вливать.

2023-03-11 19:28 UTC, nikiniki1 commented
> Дамир проверил все примеры, ничего не ломается, вроде. Исправь мои два коммента, сделай ребейз, разреши конфликты, да и можно вливать.

Сделано

2023-03-12 12:39 UTC, SuperSashka approved these changes
Давайте пробовать мержить, лучше уже не будет.

2023-03-13 10:48 UTC, merged