Add files via upload
ITMO-NSS-team/torch_DE_solver pull request #3
Opened 2022-03-15 13:10 UTC by nikiniki1

2022-03-15 13:12 UTC, nicl-nno commented
Лучшие избегать таких заголовков PR-ов и описаний коммитов.

![image](https://user-images.githubusercontent.com/5711814/158385177-587c7a0a-91a3-42cf-ba20-4254d39df789.png)

2022-03-16 09:10 UTC, SuperSashka commented
В мейн добавим после моего коммита с интерфейсом. Потом надо будет сделать ребейз, и дальше уже погнали.

2022-04-01 13:19 UTC, SuperSashka commented on README.md
> +* example_ODE.py - Legendre polynomial generator equation
Нужно обновить на актуальную версию.

2022-04-01 13:20 UTC, SuperSashka commented on cache.py
> +        # model.eval()
Тут нужно разобраться, как это работает, а не просто комментить строки.

2022-04-01 13:26 UTC, SuperSashka requested changes
Нужно удалить testing.ipynb и разобраться с кэшем+readme.md. А так вроде норм.

2022-05-12 20:23 UTC, SuperSashka approved these changes

2022-05-12 20:24 UTC, merged

2022-05-12 20:24 UTC, SuperSashka commented
Ну ок, выглядит как будто всё работает теперь. Пофиксил мелкие неточности.