Add PINNacle examples
ITMO-NSS-team/torch_DE_solver pull request #49
Opened 2024-12-09 10:35 UTC by dimerf99

Adding PINNacle benchmark examples with some changes in TEDEouS code

2024-12-09 14:49 UTC, SuperSashka commented
At first, a rebase on the main branch is needed.

2024-12-09 15:04 UTC, SuperSashka requested changes
There is a critical problem in a basic functional. It should be handled first.

2024-12-09 15:04 UTC, SuperSashka commented on tedeous/data.py
> +        grid = check_device(torch.tensor(np.array(grid)))
Setting solver_device('gpu') throws an exception here:

>can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

2024-12-10 11:31 UTC, SuperSashka requested changes

2024-12-10 11:31 UTC, SuperSashka commented on tedeous/callbacks/plot.py
> +                    axes[i].plot_trisurf(grid_x[coord_3_mask], grid_y[coord_3_mask], z_values,
example_navier_stokes_2d_TG_vortex.py throws error here:

>TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

We should handle check device stuff here thoughout

2024-12-22 22:14 UTC, florentiner commented on tedeous/callbacks/plot.py
> +    def _init_nvars_model(self):
добавить описание функции

2024-12-22 22:16 UTC, florentiner commented on tedeous/callbacks/plot.py
> +            t_values (List[float]): List of time points to plot the solution for.
в определении функции и в описание имя переменной отличается

2024-12-22 22:51 UTC, florentiner commented on tedeous/callbacks/plot.py
> +            if self.img_dim == '3d':
правильно ли понял логику что у всех с img_dim=3d projection тоже 3d должна быть (а то в оригиналне не так)

2024-12-22 22:55 UTC, florentiner commented on tedeous/callbacks/plot.py
> +        if self.img_dim == '3d':
нормально ли что добавил для все (в оригинале для img_dim=3d не было)

2024-12-22 22:58 UTC, florentiner commented on tedeous/callbacks/plot.py
> +                                        origin='lower', cmap=cm.jet, aspect='auto')
im не используется нигде. Если так и надо то надо убрать присвоение, если нет то пофиксить

2024-12-22 23:01 UTC, florentiner commented on tedeous/callbacks/plot.py
> +            t_values (List[float]): List of time points to plot the solution for.
тоже что и выше

2024-12-22 23:25 UTC, florentiner commented on tedeous/input_preprocessing.py
>              bpos.append(point_pos)
в предыдущей версии отступ другого уровня. Это фикс или опечатка?

2024-12-22 23:28 UTC, florentiner commented on tedeous/model.py
> +            removed_domains: List = None):
добавить removed_domains к описанию

2024-12-22 23:37 UTC, florentiner commented on tedeous/utils.py
> +def exact_solution_data(grid, datapath, pde_dim_in, pde_dim_out, t_dim_flag=False):
добавить описание функции

2024-12-22 23:37 UTC, florentiner commented on tedeous/utils.py
> +def init_data(grid, datapath):
так же добавить описание функции

2024-12-22 23:38 UTC, florentiner commented on tedeous/data_CSG.py
> +""" Module for construct a domain with complex geometry"""
везде добавить описание функции

2024-12-22 23:42 UTC, florentiner requested changes
add comments and changes (exept examples)

2024-12-24 13:16 UTC, florentiner commented on tedeous/callbacks/plot.py
> +                    fig.colorbar(im, ax=axes[i])
поменять на: 
if self.img_dim != '3d': fig.colorbar(scatter, ax=axes[i])

2024-12-27 13:17 UTC, SuperSashka approved these changes
It seems that we are good to go as for now.

2025-05-06 14:08 UTC, closed without merging